version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # port AMQP untuk aplikasi
      - "15672:15672"    # port untuk web management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
volumes:
  rabbitmq_data:
