version: '3.7'

services:
  apache:
    image: php:7.4-apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - xampp_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - xampp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - xampp_network

networks:
  xampp_network:
    driver: bridge
